# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Harpreet/Documents/CMPE100/Lab7/.Xil/Vivado-1064-Harpreet-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/m4_1e.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/FullAdder.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/new/m2_1x8.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/eight_bit_adder.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/count4L.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/imports/new/SignChanger.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/count16L.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/DownCounter.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/m8_1e.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/LFSR.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/Ball_Control.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/Turkey_Counter.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/EdgeDetector.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/CMPE100/Lab3_Fin/Lab3/Lab3_copy.srcs/sources_1/imports/sources_1/new/hex7seg.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/selector.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/RingCounter.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/Ball.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/Paddle.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/Sync.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/imports/Desktop/lab7_clks.v
      C:/Users/Harpreet/Documents/CMPE100/Lab7/Lab7.srcs/sources_1/new/top_level.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_level
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Harpreet/Documents/CMPE100/Lab7/.Xil/Vivado-1064-Harpreet-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
