# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.cache/wt [current_project]
set_property parent.project_path C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/m4_1e.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/FullAdder.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/new/m2_1x8.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/eight_bit_adder.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/count4L.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/imports/new/SignChanger.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/count16L.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/DownCounter.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/new/m8_1e.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/LFSR.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/Ball_Control.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/hsingh18/Downloads/Lab_6_Done.xpr/Lab_6/Lab_6.srcs/sources_1/new/Turkey_Counter.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/EdgeDetector.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/imports/CMPE100/Lab3_Fin/Lab3/Lab3_copy.srcs/sources_1/imports/sources_1/new/hex7seg.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/selector.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/sources_1/new/RingCounter.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/Ball.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/Paddle.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/Sync.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/imports/Desktop/lab7_clks.v
  C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/sources_1/new/top_level.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/hsingh18/Desktop/Lab7_Done.xpr/Lab7/Lab7.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top top_level -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
